import { Button } from '@styles/components/Button';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button color="secondary">Start Free Trial</Button>
      </main>

      <footer>footer</footer>
    </div>
  );
};

export default Home;
