import type { NextPage } from 'next';
import Head from 'next/head';
import { styled } from '@/styles/index';

const Text = styled('p', {
  color: '$green2',
  fontSize: '$xlarge',
  fontFamily: '$handwritting',
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Text>Hello darling</Text>
      </main>

      <footer>footer</footer>
    </div>
  );
};

export default Home;
