import type { NextPage } from 'next';
import Head from 'next/head';
import { Brands } from '@/components/Brands/Brands';
import { Platform } from '@/components/Platform';
import { JoinUs } from '@/components/JoinUs';
import { Footer } from '@/components/Footer';

import { Container } from '@styles/components/Container';
import { Tabs } from '@/components/Tabs';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Tabs />
        <Brands />
        <Platform />
        <JoinUs />
      </Container>
      <Footer />
    </div>
  );
};

export default Home;
